apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423611293:role/KarpenterNodeRole-zeks0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423611293:role/eksctl-zeks0-nodegroup-zeks0-ng-NodeInstanceRole-v53OjH8KaIXl
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-05T07:40:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1423"
  uid: 3d7443ef-7d1e-45f0-ad09-3eb9ed7327e1
