apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: po
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: quay.io/brancz/prometheus-example-app:v0.5.0
        ports:
        - name: web
          containerPort: 8080
