apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  namespace: po
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - interval: 30s
    port: "8080"
    path: /metrics
  namespaceSelector:
    matchNames:
    - po
