apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-prometheus-server
  namespace: po
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      name: prometheus-server
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - po
