apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-prom-node-exporter-metrics
  namespace: po
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  endpoints:
  - interval: 30s
    port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - p
