prometheus:
  prometheusSpec:
    remoteWrite:
    - url: "https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push"
      basicAuth:
          username:
            name: kubepromsecret
            key: username
          password:
            name: kubepromsecret
            key: password
