apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  # namespace: keda-test
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID
    name: aws-secrets        
    key: AWS_ACCESS_KEY_ID   
  - parameter: awsSecretAccessKey
    name: aws-secrets           
    key: AWS_SECRET_ACCESS_KEY