apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  finalizers:
    - istio-finalizer.install.istio.io
  name: istio-controlplane
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    egressGateways:
      - enabled: true
        name: istio-egressgateway
        namespace: istio-system
        k8s:
          replicaCount: 2
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        namespace: istio-system
        k8s:
          replicaCount: 2
    pilot:
      enabled: true
  profile: default
  values:
    global:
      proxy:
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
    pilot:
      replicaCount: 2

# istioctl manifest generate --set profile=demo

# https://acagroup.be/en/blog/how-to-install-istio-service-mesh-a-comprehensive-step-by-step-guide/

# install eks add on istio https://docs.solo.io/gloo-mesh-enterprise/main/istio/eks_addon/#install 

# https://medium.com/@devopsrockers/deploying-istio-with-nlb-in-eks-using-helm-6f07928c3ab3

# https://archive.eksworkshop.com/advanced/310_servicemesh_with_istio/install/

# helm install -n istio-system istio-base istio-1.23.0/manifests/charts/base
# helm status istio-base -n istio-system
# helm get all istio-base -n istio-system

# helm install -n istio-system istiod istio-1.23.0/manifests/charts/istio-control/istio-discovery
# helm status istiod -n istio-system
# helm get all istiod -n istio-system

# Next steps:
#   * Deploy a Gateway: https://istio.io/latest/docs/setup/additional-setup/gateway/
#   * Try out our tasks to get started on common configurations:
#     * https://istio.io/latest/docs/tasks/traffic-management
#     * https://istio.io/latest/docs/tasks/security/
#     * https://istio.io/latest/docs/tasks/policy-enforcement/
#   * Review the list of actively supported releases, CVE publications and our hardening guide:
#     * https://istio.io/latest/docs/releases/supported-releases/
#     * https://istio.io/latest/news/security/
#     * https://istio.io/latest/docs/ops/best-practices/security/

# helm install -n istio-system istio-ingress istio-1.23.0/manifests/charts/gateways/istio-ingress
# service\.beta\.kubernetes\.io/aws-load-balancer-proxy-protocol"="*" \
# service\.beta\.kubernetes\.io/aws-load-balancer-connection-idle-timeout"="60" \
# service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled"="true" \
# service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb"

# kubectl label namespace default istio-injection=enabled

# helm list -aq -n istio-system
# helm uninstall -n istio-system istio-ingress

# https://github.com/istio/istio/issues/11131