apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: po
  labels:
    name: prometheus-server
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - name: http
      port: 8080
      targetPort: 9090 
      nodePort: 30000
