apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-telemetry
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
    customTags:
      cluster_nm:
        literal:
          value: "eksv1"
